name: WakaTime Weekly Stats

on:
  schedule:
    # Runs once a day at 00:30 UTC
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with WakaTime stats
        uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494 # v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TARGET_PATH: README.md
          SHOW_TITLE: "false"
          BLOCKS: "░▒▓█"
          TIME_RANGE: last_7_days
